#!/bin/bash

set -e

# detect conda/mamba and set CONDA_COMMAND and CONDA_ENV
SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
source "$SCRIPT_DIR/_detect_conda.sh"

# run command from root of totp project folder
SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
cd $SCRIPT_DIR/..

$CONDA_COMMAND run -n $CONDA_ENV --no-capture-output python -m src.start_ssh "$@"
