#!/bin/bash

set -euo pipefail

# This script will clean up everything which TOTP set during the initial setup steps
# including: MacOS keychaing passwords, ~/.zshrc changes, and ~/.ssh/config changes

# detect conda/mamba and set CONDA_COMMAND and CONDA_ENV
SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")
source "$SCRIPT_DIR/_detect_conda.sh"

SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )")

cd $SCRIPT_DIR/..

$CONDA_COMMAND run -n $CONDA_ENV --no-capture-output python -m src.cleanup_all
